global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'tkmprom'
    static_configs:
      - targets: ['home.home:9091']
    scrape_interval: 30s
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself
    scrape_interval: 30s
